export const TalkCategories = [
  "Campus Buzz",
  "Coding Errors",
  "9ja Wahala",
  "Loan apps ",
  // "Gossip",
  // "Japa Trends in Nigeria",
  "Sports betting",
  "Relationships",
  "Sex Story ",
  "Unilag gist",
  "Ibadan UI Pulse",
  "Lecturer Stories",
  "Anime",
  "World Talks",
  "Crypto Gist",
  "Religion & Society",
  "Japa Trends in Ghana",
  "School Diaries",
  "Business in Ghana",
  "Business in General",
  "Culture",
  "Cybersecurity",
  "Bad Girl Stories",
  "Bad Boy Stories",
  "XXX",
  "Economy",
  "Women Orgams",
  "entertainment",
  "Business in Ireland",
  "Exchange Rate ",
  "Entrepreneurship",
  "Fashion",
  "food",
  "Job Opportunities",
  "Health",
  "Movies",
  "Music",
  "Online market place",
  "politics",
  "Real Estate News ",
  "Religion",
  "Frontend Development",
  "Backend Development",
  "Technology",
  "Travel",
];

export const TweetCategories = [
  "ApartmentTweet",
  "ArtTweet",
  "BeautyTweet",
  "BusinessTweet",
  "Create +18",
  "CarTweet",
  "CarUpgradeTweet",
  "CodingTweet",
  "EducationTweet",
  "EventTweet",
  "FashionTweet",
  "FitnessTweet",
  "FoodTweet",
  "FragranceTweet",
  "GadgetTweet",
  "GamingTweet",
  "HealthTweet",
  "MingleTweet",
  "MusicTweet",
  "PetTweet",
  "SkincareTweet",
  "SportsTweet",
  "TechTweet",
  "TravelTweet",
];
